services:
  db:
    image: postgres:15
    container_name: imager_test_db
    ports:
      - "${TEST_DB_PORT}:${TEST_DB_PORT}"
    environment:
      - POSTGRES_USER=${TEST_DB_USER}
      - POSTGRES_PASSWORD=${TEST_DB_PASS}
      - POSTGRES_DB=${TEST_DB_NAME}
      - PGPORT=${TEST_DB_PORT}