services:
  db:
    platform: linux/amd64
    image: postgres:15
    container_name: imager_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "${DB_PORT}:${DB_PORT}"
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
      - POSTGRES_DB=${DB_NAME}
      - PGPORT=${DB_PORT}
  imager_bot:
    platform: linux/amd64
    build:
      context: .
      dockerfile: Dockerfile
    container_name: imager_bot
    entrypoint: /bin/sh
    volumes:
      - selenium_drivers:/root/.cache/selenium:Z
    command: -c 'alembic upgrade head && python imager_bot/init_db.py &&python imager_bot/main.py'
    env_file:
      - .env
    depends_on:
      - db

volumes:
  postgres_data: {}
  selenium_drivers: {}
